trigger:
- main

pool:
  vmImage: 'Default'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:
      
      - script: npm install
        displayName: 'Install Dependencies'

      
      - task: Npm@1
        inputs:
          command: 'test'
        displayName: 'Run Unit Tests'